### ISSUE TITLE
Access at two endpoint

### ISSUE THREAD

**Issue by art-tom** [scampi/gosparqled#47]
Hello,

I have a question, I use your developpement and I need to connect two endpoint for one application.
In fact one connection for a specify schema (and autocompletion) and second connection for query.
I search on this code but I have not see where I add the function.

Thank in advance.

**Comment by scampi** [comment]
The UI proposed in `demo` is really basic and so most of the configurations are hard coded. Therefore, you'd need to do some bit of tinkering:

- setting the endpoint for the query: https://github.com/scampi/gosparqled/blob/master/demo/autocompletion.js#L103
- setting the endpoint for the autocompletion: https://github.com/scampi/gosparqled/blob/master/demo/autocompletion.js#L30

**Comment by art-tom** [comment]
Thank it's good

:)
